name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get AVIDEOGRAVADO.m3u8
      run: |
        touch ./AVIDEOGRAVADO.m3u8
        sudo cat >./AVIDEOGRAVADO.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=zpu4GaM4j4k)
        EOL
    - name: Get ALIVERECORDJAPAN.m3u8
      run: |
        touch ./ALIVERECORDJAPAN.m3u8
        sudo cat >./ALIVERECORDJAPAN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/c/RECORDTVJAPAN/live)
        EOL
    - name: Get ACNNVENEZUELA.m3u8
      run: |
        touch ./ACNNVENEZUELA.m3u8
        sudo cat >./ACNNVENEZUELA.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/c/cnnee/live)
        EOL
    - name: Get MashaandtheBear.m3u8
      run: |
        touch ./MashaandtheBear.m3u8
        sudo cat >./MashaandtheBear.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/channel/UCCqX_4VAN8RE_Jz8vlIGEUw/live)
        EOL
    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
