name: Get StreamLink Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install streamlink
      run : |
        sudo apt update -y
        sudo pip install streamlink   
    - name: Get TVIREALITY.m3u8
      run: |
        touch ./TVIREALITY.m3u8
        sudo cat >./TVIREALITY.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(streamlink --url --default-stream  --output "~/youtube.m3u" https://www.youtube.com/watch?v=X0yB1Nxv99I best)
        EOL
        
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
